name: Deploy contabil-usuario

on:
  push:
    branches:
      - master

jobs:
  deploy:
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      service-name: contabil-usuario
      deployment-name: contabil-usuario-deployment
      port: "10091"
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      TAILSCALE_OAUTH_CLIENT_ID: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
      TAILSCALE_OAUTH_SECRET: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
